version: "3.3"
services:
  binotify-app-web:
    build: .
    image: binotify-app-web:latest
    volumes:
      - ./src:/var/www/html
    ports:
      - ${BINOTIFY_APP_WEB_PORT:-8008}:80

  binotify-app-db:
    image: postgres:latest
    restart: always
    ports:
      - ${BINOTIFY_APP_DB_PORT:-15432}:5432
    environment:
      - POSTGRES_PASSWORD=${BINOTIFY_APP_DB_PASSWORD:-postgres}
      - POSTGRES_DB=${BINOTIFY_APP_DB_NAME:-database}
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
